# Generated by Django 4.1 on 2022-09-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='om',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
