# Generated by Django 4.1.1 on 2022-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0003_alter_post_description_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='creator',
            name='profile_pic',
            field=models.CharField(default='no pic', max_length=100),
        ),
    ]
