# Generated by Django 4.1 on 2022-09-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0005_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
    ]
