# Generated by Django 4.1 on 2022-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0008_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='no file', upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='no profile picture', upload_to='user/'),
        ),
    ]
