# Generated by Django 4.1 on 2022-09-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0011_dailywords_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywords',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_words', to='preSent.creator'),
        ),
    ]
