# Generated by Django 4.1 on 2022-09-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0012_alter_dailywords_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post/%Y/%m/%D/'),
        ),
    ]
