# Generated by Django 4.1 on 2022-09-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0016_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.CharField(blank=True, default='no file available', max_length=200, null=True),
        ),
    ]
