# Generated by Django 4.1 on 2022-09-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0017_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
