# Generated by Django 4.1 on 2022-09-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0018_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
