# Generated by Django 4.1 on 2022-09-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0019_alter_creator_profile_pic_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
    ]
