# Generated by Django 4.1 on 2022-09-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0021_alter_post_file_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
