# Generated by Django 4.1 on 2022-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0022_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
