# Generated by Django 4.1 on 2022-09-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0025_alter_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
