# Generated by Django 4.1 on 2022-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0026_remove_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tempcomment',
            field=models.TextField(null=True),
        ),
    ]
