# Generated by Django 4.1 on 2022-09-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0027_post_tempcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tempcomment',
        ),
    ]
