# Generated by Django 4.1 on 2022-09-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0028_remove_post_tempcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
