# Generated by Django 4.1 on 2022-09-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0029_remove_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
