# Generated by Django 4.1 on 2022-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0032_remove_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='oms',
            field=models.IntegerField(default=0),
        ),
    ]
