# Generated by Django 4.1 on 2022-09-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0033_post_oms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='oms',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
