# Generated by Django 4.1 on 2022-09-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preSent', '0034_alter_post_oms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='oms',
        ),
    ]
